CREATE TABLESPACE seguimiento
   DATAFILE 'seguimiento.dbf' 
   SIZE 10m; 

 CREATE TEMPORARY TABLESPACE seguimiento_temp
   TEMPFILE 'seguimiento_temp.dbf'
   SIZE 10m;

 CREATE USER seguimiento
    IDENTIFIED BY seguimiento
    DEFAULT TABLESPACE seguimiento
    TEMPORARY TABLESPACE seguimiento_temp;

GRANT CREATE SESSION, ALTER SESSION, CREATE DATABASE LINK, 
  CREATE MATERIALIZED VIEW, CREATE PROCEDURE, CREATE PUBLIC SYNONYM, 
  CREATE ROLE, CREATE SEQUENCE, CREATE SYNONYM, CREATE TABLE, 
  CREATE TRIGGER, CREATE TYPE, CREATE VIEW, UNLIMITED TABLESPACE 
  TO seguimiento;