CREATE TABLESPACE TRANSACCIONES
	DATAFILE 'transacciones.dbf'
	SIZE 10m
	AUTOEXTEND ON
		-- No tenemos tanto disco
		--MAXSIZE 51231m;
		MAXSIZE 20m;

ALTER TABLE SEGUIMIENTO.SOLICITUD MOVE TABLESPACE TRANSACCIONES;
ALTER TABLE SEGUIMIENTO.ABONO MOVE TABLESPACE TRANSACCIONES;

ALTER INDEX SEGUIMIENTO.SOLICITUD_PK REBUILD;
ALTER INDEX SEGUIMIENTO.ABONO_PK REBUILD;