CREATE OR REPLACE VIEW ABONO_VISTA AS (
	SELECT a.ID_MOVIMIENTO , a.ID_PRODUCTO 
		FROM ABONO a 
);

CREATE OR REPLACE VIEW SOLICITUD_VISTA AS (
	SELECT s.ID_SOLICITUD , s.FECHA , s.CEDULA_PERSONA , s.CEDULA_EMPLEADO , s.ID_TIPO , s.ID_PRODUCTO, s.ACEPTADA
		FROM SOLICITUD s 
);