-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.solicitud
(
    id_solicitud integer NOT NULL GENERATED ALWAYS AS IDENTITY,
    fecha date NOT NULL,
    cedula_cliente character varying(20) NOT NULL,
    cedula_empleado character varying(20) NOT NULL,
    id_tipo character varying(20),
    id_producto character varying(20) NOT NULL,
    PRIMARY KEY (id_solicitud)
);

CREATE TABLE IF NOT EXISTS public.abono
(
    id_movimiento integer NOT NULL GENERATED ALWAYS AS IDENTITY,
    id_producto character varying(24) NOT NULL
);
END;