-- Caja 
INSERT INTO FINANCIERA.CAJA
(ID_CAJA, NOMBRE, SUCURSAL_ID_SUCURSAL)
VALUES(1, 'Caja 1', 1);
INSERT INTO FINANCIERA.CAJA
(ID_CAJA, NOMBRE, SUCURSAL_ID_SUCURSAL)
VALUES(2, 'Caja 2', 1);
INSERT INTO FINANCIERA.CAJA
(ID_CAJA, NOMBRE, SUCURSAL_ID_SUCURSAL)
VALUES(3, 'Caja 3', 1);
INSERT INTO FINANCIERA.CAJA
(ID_CAJA, NOMBRE, SUCURSAL_ID_SUCURSAL)
VALUES(4, 'Caja 4', 1);
INSERT INTO FINANCIERA.CAJA
(ID_CAJA, NOMBRE, SUCURSAL_ID_SUCURSAL)
VALUES(5, 'Caja 5', 1);
INSERT INTO FINANCIERA.CAJA
(ID_CAJA, NOMBRE, SUCURSAL_ID_SUCURSAL)
VALUES(6, 'Caja 1', 2);
INSERT INTO FINANCIERA.CAJA
(ID_CAJA, NOMBRE, SUCURSAL_ID_SUCURSAL)
VALUES(7, 'Caja 2', 2);
INSERT INTO FINANCIERA.CAJA
(ID_CAJA, NOMBRE, SUCURSAL_ID_SUCURSAL)
VALUES(8, 'Caja 3', 2);
INSERT INTO FINANCIERA.CAJA
(ID_CAJA, NOMBRE, SUCURSAL_ID_SUCURSAL)
VALUES(9, 'Caja 4', 2);
INSERT INTO FINANCIERA.CAJA
(ID_CAJA, NOMBRE, SUCURSAL_ID_SUCURSAL)
VALUES(10, 'Caja 5', 2);
INSERT INTO FINANCIERA.CAJA
(ID_CAJA, NOMBRE, SUCURSAL_ID_SUCURSAL)
VALUES(11, 'Caja 1', 3);
INSERT INTO FINANCIERA.CAJA
(ID_CAJA, NOMBRE, SUCURSAL_ID_SUCURSAL)
VALUES(12, 'Caja 2', 3);
INSERT INTO FINANCIERA.CAJA
(ID_CAJA, NOMBRE, SUCURSAL_ID_SUCURSAL)
VALUES(13, 'Caja 3', 3);
INSERT INTO FINANCIERA.CAJA
(ID_CAJA, NOMBRE, SUCURSAL_ID_SUCURSAL)
VALUES(14, 'Caja 4', 3);
INSERT INTO FINANCIERA.CAJA
(ID_CAJA, NOMBRE, SUCURSAL_ID_SUCURSAL)
VALUES(15, 'Caja 5', 3);
INSERT INTO FINANCIERA.CAJA
(ID_CAJA, NOMBRE, SUCURSAL_ID_SUCURSAL)
VALUES(16, 'Caja 1', 4);
INSERT INTO FINANCIERA.CAJA
(ID_CAJA, NOMBRE, SUCURSAL_ID_SUCURSAL)
VALUES(17, 'Caja 2', 4);
INSERT INTO FINANCIERA.CAJA
(ID_CAJA, NOMBRE, SUCURSAL_ID_SUCURSAL)
VALUES(18, 'Caja 3', 4);
INSERT INTO FINANCIERA.CAJA
(ID_CAJA, NOMBRE, SUCURSAL_ID_SUCURSAL)
VALUES(19, 'Caja 4', 4);
INSERT INTO FINANCIERA.CAJA
(ID_CAJA, NOMBRE, SUCURSAL_ID_SUCURSAL)
VALUES(20, 'Caja 5', 4);
INSERT INTO FINANCIERA.CAJA
(ID_CAJA, NOMBRE, SUCURSAL_ID_SUCURSAL)
VALUES(21, 'Caja 1', 5);
INSERT INTO FINANCIERA.CAJA
(ID_CAJA, NOMBRE, SUCURSAL_ID_SUCURSAL)
VALUES(22, 'Caja 2', 5);
INSERT INTO FINANCIERA.CAJA
(ID_CAJA, NOMBRE, SUCURSAL_ID_SUCURSAL)
VALUES(23, 'Caja 3', 5);
INSERT INTO FINANCIERA.CAJA
(ID_CAJA, NOMBRE, SUCURSAL_ID_SUCURSAL)
VALUES(24, 'Caja 4', 5);
INSERT INTO FINANCIERA.CAJA
(ID_CAJA, NOMBRE, SUCURSAL_ID_SUCURSAL)
VALUES(25, 'Caja 5', 5);
