CREATE TABLESPACE PARAMETRICAS
	DATAFILE 'parametricas.dbf'
	SIZE 1m
	AUTOEXTEND ON
		MAXSIZE 101m;
		
CREATE TABLESPACE PRODUCTOS
	DATAFILE 'productos.dbf'
	SIZE 10m
	AUTOEXTEND ON 
		MAXSIZE 12074m;
		
CREATE TABLESPACE TRANSACCIONES
	DATAFILE 'transacicones.dbf'
	SIZE 10m
	AUTOEXTEND ON
		-- No tenemos tanto disco duro
		--MAXSIZE 700455m;
		MAXSIZE 20m;