CREATE TABLESPACE PARAMETRICAS
	DATAFILE 'parametricas.dbf'
	SIZE 1m
	AUTOEXTEND ON
		MAXSIZE 101m;
		
CREATE TABLESPACE PRODUCTOS
	DATAFILE 'productos.dbf'
	SIZE 10m
	AUTOEXTEND ON 
		MAXSIZE 12074m;
		
CREATE TABLESPACE TRANSACCIONES
	DATAFILE 'transacicones.dbf'
	SIZE 10m
	AUTOEXTEND ON
		-- No tenemos tanto disco duro
		--MAXSIZE 700455m;
		MAXSIZE 20m;

ALTER TABLE FINANCIERA.FORMA_PAGO MOVE TABLESPACE PARAMETRICAS;
ALTER TABLE FINANCIERA.CAJA MOVE TABLESPACE PARAMETRICAS;
ALTER TABLE FINANCIERA.EMPRESA MOVE TABLESPACE PARAMETRICAS;

ALTER INDEX FINANCIERA.FORMA_PAGO_PK REBUILD;
ALTER INDEX FINANCIERA.CAJA_PK REBUILD;
ALTER INDEX FINANCIERA.EMPRESA_PK REBUILD;


ALTER TABLE FINANCIERA.SEGURO MOVE TABLESPACE PRODUCTOS;
ALTER TABLE FINANCIERA.CREDITO MOVE TABLESPACE PRODUCTOS;
ALTER TABLE FINANCIERA.TARJETA_DE_CREDITO MOVE TABLESPACE PRODUCTOS;
ALTER TABLE FINANCIERA.CUENTA MOVE TABLESPACE PRODUCTOS;
ALTER TABLE FINANCIERA.PRODUCTO MOVE TABLESPACE PRODUCTOS;

ALTER INDEX FINANCIERA.SEGURO_PK REBUILD;
ALTER INDEX FINANCIERA.CREDITO_PK REBUILD;
ALTER INDEX FINANCIERA.TARJETA_DE_CREDITO_PK REBUILD;
ALTER INDEX FINANCIERA.CUENTA_PK REBUILD;
ALTER INDEX FINANCIERA.PRODUCTO_PK REBUILD;


ALTER TABLE FINANCIERA.RETIRO MOVE TABLESPACE TRANSACCIONES;
ALTER TABLE FINANCIERA.TRANSFERENCIA MOVE TABLESPACE TRANSACCIONES;
ALTER TABLE FINANCIERA.MOVIMIENTO MOVE TABLESPACE TRANSACCIONES;
ALTER TABLE FINANCIERA.CONSIGNACION MOVE TABLESPACE TRANSACCIONES;
ALTER TABLE FINANCIERA.PAGO MOVE TABLESPACE TRANSACCIONES;

ALTER INDEX FINANCIERA.RETIRO_PK REBUILD;
ALTER INDEX FINANCIERA.TRANSFERENCIA_PK REBUILD;
ALTER INDEX FINANCIERA.MOVIMIENTO_PK REBUILD;
ALTER INDEX FINANCIERA.CONSIGNACION_PK REBUILD;
ALTER INDEX FINANCIERA.PAGO_PK REBUILD;