CREATE TABLESPACE PARAMETRICAS
	DATAFILE 'parametricas.dbf'
	SIZE 10m
	AUTOEXTEND ON
		MAXSIZE 421m;
		
CREATE TABLESPACE EMPLEADOS_CLIENTES
	DATAFILE 'empleados_clientes.dbf'
	SIZE 10m
	AUTOEXTEND ON
		MAXSIZE 6899m;
		
CREATE TABLESPACE VENTAS
	DATAFILE 'ventas.dbf'
	SIZE 10m
	AUTOEXTEND ON
		-- No tenemos un disco de 2TB
		-- MAXSIZE 1903418m;
		MAXSIZE 100m;


CREATE TABLESPACE TRANSACCIONES
	DATAFILE 'transacciones.dbf'
	SIZE 10m
	AUTOEXTEND ON 
		-- No tenemos un disco de 51GB
		--MAXSIZE 51231m;
		MAXSIZE 100m;