CREATE PROFILE PERFIL_CAJERO
	LIMIT
		IDLE_TIME 5
		PASSWORD_LIFE_TIME 3
		PASSWORD_GRACE_TIME 1;
		
CREATE USER USUARIO_CAJERO
	IDENTIFIED BY usuario_cajero
	PROFILE PERFIL_CAJERO
	DEFAULT TABLESPACE FINANCIERA
	TEMPORARY TABLESPACE FINANCIERA_TEMP;

CREATE PROFILE PERFIL_CLIENTE
	LIMIT 
		IDLE_TIME 20;
		
CREATE USER USUARIO_CLIENTE 
	IDENTIFIED BY usuario_cliente
	PROFILE PERFIL_CLIENTE
	DEFAULT TABLESPACE FINANCIERA
	TEMPORARY TABLESPACE FINANCIERA_TEMP;

CREATE PROFILE PERFIL_JEFE_OFICINA
	LIMIT 
		FAILED_LOGIN_ATTEMPTS 1
		PASSWORD_LOCK_TIME 3
		PASSWORD_LIFE_TIME 7
		PASSWORD_GRACE_TIME 1;
		
CREATE USER USUARIO_JEFE_OFICINA
	IDENTIFIED BY usuario_jefe_oficina
	PROFILE PERFIL_JEFE_OFICINA
	DEFAULT TABLESPACE FINANCIERA
	TEMPORARY TABLESPACE FINANCIERA_TEMP;

CREATE PROFILE PERFIL_ANALISTA_CREDITOS
	LIMIT
		FAILED_LOGIN_ATTEMPTS 3
		PASSWORD_LOCK_TIME 2;
		
CREATE USER USUARIO_ANALISTA_CREDITOS
	IDENTIFIED BY usuario_analista_creditos
	PROFILE PERFIL_ANALISTA_CREDITOS
	DEFAULT TABLESPACE FINANCIERA
	TEMPORARY TABLESPACE FINANCIERA_TEMP;