GRANT SELECT ON FINANCIERA.MOVIMIENTO_VISTA TO USUARIO_CLIENTE;

GRANT SELECT ON FINANCIERA.PRODUCTO_VISTA TO USUARIO_CLIENTE;

GRANT SELECT ON FINANCIERA.FORMA_PAGO_VISTA TO USUARIO_CLIENTE;

GRANT SELECT ON FINANCIERA.EMPRESA_VISTA TO USUARIO_CLIENTE;

GRANT SELECT ON FINANCIERA.TARJETA_CREDITO_VISTA TO USUARIO_CLIENTE;

GRANT SELECT ON FINANCIERA.CONSIGNACION_VISTA TO USUARIO_CLIENTE;

GRANT SELECT ON FINANCIERA.CREDITO_VISTA TO USUARIO_CLIENTE;

GRANT SELECT ON FINANCIERA.CUENTA_VISTA TO USUARIO_CLIENTE;

GRANT SELECT ON FINANCIERA.PAGO_VISTA TO USUARIO_CLIENTE;

GRANT SELECT ON FINANCIERA.SEGURO_VISTA TO USUARIO_CLIENTE;

GRANT SELECT ON FINANCIERA.TRANSFERENCIA_VISTA TO USUARIO_CLIENTE;


GRANT SELECT ON FINANCIERA.MOVIMIENTO_VISTA TO USUARIO_CAJERO;

GRANT SELECT ON FINANCIERA.PRODUCTO_VISTA TO USUARIO_CAJERO;

GRANT SELECT ON FINANCIERA.FORMA_PAGO_VISTA TO USUARIO_CAJERO;

GRANT SELECT ON FINANCIERA.EMPRESA_VISTA TO USUARIO_CAJERO;

GRANT SELECT ON FINANCIERA.CONSIGNACION_VISTA TO USUARIO_CAJERO;

GRANT SELECT ON FINANCIERA.CREDITO_VISTA TO USUARIO_CAJERO;

GRANT SELECT ON FINANCIERA.CUENTA_VISTA TO USUARIO_CAJERO;

GRANT SELECT ON FINANCIERA.PAGO_VISTA TO USUARIO_CAJERO;

GRANT SELECT ON FINANCIERA.SEGURO_VISTA TO USUARIO_CAJERO;

GRANT SELECT ON FINANCIERA.TRANSFERENCIA_VISTA TO USUARIO_CAJERO;

GRANT SELECT ON FINANCIERA.CAJA_VISTA TO USUARIO_CAJERO;

GRANT SELECT ON FINANCIERA.RETIRO_VISTA TO USUARIO_CAJERO;


GRANT SELECT ON FINANCIERA.MOVIMIENTO_VISTA TO USUARIO_JEFE_OFICINA;

GRANT SELECT, INSERT ON FINANCIERA.PRODUCTO_VISTA TO USUARIO_JEFE_OFICINA;

GRANT SELECT ON FINANCIERA.FORMA_PAGO_VISTA TO USUARIO_JEFE_OFICINA;

GRANT SELECT ON FINANCIERA.EMPRESA_VISTA TO USUARIO_JEFE_OFICINA;

GRANT SELECT, INSERT ON FINANCIERA.TARJETA_CREDITO_VISTA TO USUARIO_JEFE_OFICINA;

GRANT SELECT ON FINANCIERA.CONSIGNACION_VISTA TO USUARIO_JEFE_OFICINA;

GRANT SELECT, INSERT ON FINANCIERA.CREDITO_VISTA TO USUARIO_JEFE_OFICINA;

GRANT SELECT, INSERT ON FINANCIERA.CUENTA_VISTA TO USUARIO_JEFE_OFICINA;

GRANT SELECT ON FINANCIERA.PAGO_VISTA TO USUARIO_JEFE_OFICINA;

GRANT SELECT, INSERT ON FINANCIERA.SEGURO_VISTA TO USUARIO_JEFE_OFICINA;

GRANT SELECT ON FINANCIERA.TRANSFERENCIA_VISTA TO USUARIO_JEFE_OFICINA;

GRANT SELECT ON FINANCIERA.CAJA_VISTA TO USUARIO_JEFE_OFICINA;

GRANT SELECT ON FINANCIERA.RETIRO TO USUARIO_JEFE_OFICINA;


GRANT SELECT ON FINANCIERA.PRODUCTO_VISTA TO USUARIO_ANALISTA_CREDITOS;

GRANT SELECT ON FINANCIERA.FORMA_PAGO_VISTA TO USUARIO_ANALISTA_CREDITOS;

GRANT SELECT ON FINANCIERA.EMPRESA_VISTA TO USUARIO_ANALISTA_CREDITOS;

GRANT SELECT, UPDATE ON FINANCIERA.TARJETA_CREDITO_VISTA TO USUARIO_ANALISTA_CREDITOS;

GRANT SELECT, UPDATE ON FINANCIERA.CREDITO_VISTA TO USUARIO_ANALISTA_CREDITOS;

GRANT SELECT ON FINANCIERA.CUENTA_VISTA TO USUARIO_ANALISTA_CREDITOS;

GRANT SELECT ON FINANCIERA.SEGURO TO USUARIO_ANALISTA_CREDITOS;