CREATE OR REPLACE VIEW CIUDAD_VISTA AS (
	SELECT C.ID_CIUDAD , c.NOMBRE , c.ID_DEPARTAMENTO 
		FROM USUARIOS.CIUDAD c 
);

CREATE OR REPLACE VIEW CLIENTE_VISTA AS (
	SELECT p.CEDULA , p.PRIMER_NOMBRE , p.SEGUNDO_NOMBRE , p.PRIMER_APELLIDO , p.SEGUNDO_APELLIDO , p.CORREO_ELECTRONICO , p.DIRECCION , p.ID_CIUDAD 
		FROM USUARIOS.PERSONA p 
			JOIN USUARIOS.CLIENTE c ON c.CEDULA_PERSONA = p.CEDULA 
);

CREATE OR REPLACE VIEW DEPARTAMENTO_VISTA AS (
	SELECT d.NOMBRE , d.ID_DEPARTAMENTO , d.PAIS_ID 
		FROM USUARIOS.DEPARTAMENTO d 
);

CREATE OR REPLACE VIEW PAIS_VISTA AS (
	SELECT p.NOMBRE , p.ID_PAIS 
		FROM USUARIOS.PAIS p 
);

CREATE OR REPLACE VIEW EMPLEADO_VISTA AS (
	SELECT p.CEDULA , p.PRIMER_NOMBRE , p.SEGUNDO_NOMBRE , p.PRIMER_APELLIDO , p.SEGUNDO_APELLIDO , p.CORREO_ELECTRONICO , p.DIRECCION , p.ID_CIUDAD 
		FROM PERSONA p
			JOIN EMPLEADO e ON E.CEDULA_PERSONA = p.CEDULA 
);

CREATE OR REPLACE VIEW FACTURA_VISTA AS (
	SELECT f.ID_FACTURA , f.MONTO , f.FECHA_VENCIMIENTO , f.DESCRIPCION , f.ID_PRODUCTO , f.CEDULA_CLIENTE 
		FROM FACTURA f 
);

CREATE OR REPLACE VIEW PRODUCTO_OFERTADO_VISTA AS (
	SELECT po.ID_PRODUCTO , po.ID_REGISTRO , po.ACEPTADO 
		FROM PRODUCTO_OFERTADO po 
);

CREATE OR REPLACE VIEW REGISTRO_LLAMADAS_VISTA AS (
	SELECT rl.HORA_INICIO , rl.HORA_FIN , rl.ID_REGISTRO , rl.CALIFICACION , rl.CEDULA_EMPLEADO , rl.CEDULA_CLIENTE 
		FROM REGISTRO_LLAMADAS rl 
);

CREATE OR REPLACE VIEW SUCURSAL_VISTA AS (
	SELECT s.ID_SUCURSAL , s.NOMBRE , s.ID_CIUDAD 
		FROM SUCURSAL s 
);


CREATE OR REPLACE VIEW TELEFONO_VISTA AS (
	SELECT t.TELEFONO , ti.DESCRIPCION  , t.CEDULA_CLIENTE 
		FROM TELEFONO t
			JOIN TIPO ti ON ti.ID_TIPO = t.ID_TIPO 
);


CREATE OR REPLACE VIEW TIPO_VISTA AS (
	SELECT t.ID_TIPO , t.DESCRIPCION , t.CATEGORIA 
		FROM TIPO t
);

CREATE OR REPLACE VIEW TURNO_EMPLEADO_VISTA AS (
	SELECT te.CODIGO , te.HORA_INICIO , te.HORA_FIN , te.ID_CAJA , p.PRIMER_NOMBRE , p.SEGUNDO_NOMBRE , p.PRIMER_APELLIDO , p.SEGUNDO_APELLIDO 
		FROM TURNO_EMPLEADO te
			JOIN PERSONA p ON p.CEDULA = te.CEDULA_EMPLEADO
			--Hacer join a la caja
);