GRANT SELECT ON USUARIOS.CLIENTE_VISTA TO USUARIO_CLIENTE;

GRANT INSERT, SELECT, UPDATE ON USUARIOS.FACTURA_VISTA TO USUARIO_CLIENTE;

GRANT SELECT ON USUARIOS.TELEFONO_VISTA TO USUARIO_CLIENTE;

GRANT SELECT ON USUARIOS.TIPO_VISTA TO USUARIO_CLIENTE;

GRANT SELECT ON USUARIOS.PAIS_VISTA TO USUARIO_CLIENTE;

GRANT SELECT ON USUARIOS.DEPARTAMENTO_VISTA TO USUARIO_CLIENTE;

GRANT SELECT ON USUARIOS.CIUDAD_VISTA TO USUARIO_CLIENTE;


GRANT SELECT, INSERT ON USUARIOS.CLIENTE_VISTA TO USUARIO_JEFE_OFICINA;

GRANT SELECT, INSERT ON USUARIOS.TELEFONO_VISTA TO USUARIO_JEFE_OFICINA;

GRANT SELECT ON USUARIOS.TIPO_VISTA TO USUARIO_JEFE_OFICINA;

GRANT SELECT ON USUARIOS.PAIS_VISTA TO USUARIO_JEFE_OFICINA;

GRANT SELECT ON USUARIOS.DEPARTAMENTO_VISTA TO USUARIO_JEFE_OFICINA;

GRANT SELECT ON USUARIOS.CIUDAD_VISTA TO USUARIO_JEFE_OFICINA;

GRANT SELECT ON USUARIOS.EMPLEADO_VISTA TO USUARIO_JEFE_OFICINA;

GRANT SELECT ON USUARIOS.TURNO_EMPLEADO_VISTA TO USUARIO_JEFE_OFICINA;

GRANT SELECT ON USUARIOS.SUCURSAL_VISTA TO USUARIO_JEFE_OFICINA;


GRANT SELECT ON USUARIOS.CLIENTE_VISTA TO USUARIO_ANALISTA_CREDITOS;

GRANT SELECT ON USUARIOS.FACTURA_VISTA TO USUARIO_ANALISTA_CREDITOS;

GRANT SELECT ON USUARIOS.TELEFONO_VISTA TO USUARIO_ANALISTA_CREDITOS;

GRANT SELECT ON USUARIOS.TIPO_VISTA TO USUARIO_ANALISTA_CREDITOS;

GRANT SELECT ON USUARIOS.PAIS_VISTA TO USUARIO_ANALISTA_CREDITOS;

GRANT SELECT ON USUARIOS.DEPARTAMENTO_VISTA TO USUARIO_ANALISTA_CREDITOS;

GRANT SELECT ON USUARIOS.CIUDAD_VISTA TO USUARIO_ANALISTA_CREDITOS;

GRANT SELECT ON USUARIOS.SUCURSAL_VISTA TO USUARIO_ANALISTA_CREDITOS;