--Consulta haciendo uso del having 

--Enunciado: Listar los clientes cuyas cuentas de ahorro hayan tenido un mínimo de 5 movimientos y posean al menos 150.000 pesos en saldo. 

SELECT c.CEDULA_PERSONA, p.PRIMER_NOMBRE, p.PRIMER_APELLIDO, cu.PRODUCTO_ID_PRODUCTO, 
       COUNT(m.CLIENTE_PERSONA_CEDULA) AS "CANTIDAD_MOVIMIENTOS"
FROM CLIENTE c
JOIN PERSONA p
ON c.CEDULA_PERSONA = p.CEDULA 
JOIN CUENTA cu 
ON cu.CLIENTE_PERSONA_CEDULA = p.CEDULA 
JOIN TIPO t
ON cu.TIPO_ID_TIPO = t.ID_TIPO 
JOIN PRODUCTO pr 
ON pr.ID_PRODUCTO = cu.PRODUCTO_ID_PRODUCTO
JOIN MOVIMIENTO m 
ON m.CLIENTE_PERSONA_CEDULA = c.CEDULA_PERSONA 
WHERE  cu.TIPO_ID_TIPO = 13 AND cu.SALDO >= '150.000'
GROUP BY c.CEDULA_PERSONA, p.PRIMER_NOMBRE, p.PRIMER_APELLIDO, cu.PRODUCTO_ID_PRODUCTO
HAVING COUNT(m.CLIENTE_PERSONA_CEDULA) >= 5 
